In [67]:
import pandas as pd
import numpy as np
import pickle 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [68]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [69]:
data = data.drop(["RowNumber","CustomerId","Surname"],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [70]:
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])

In [71]:
ohe = OneHotEncoder(handle_unknown='ignore')
geo_encoded = ohe.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=ohe.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [72]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [73]:
# splitting the data into independent and target features
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [74]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [75]:
#saving the encoder and scalar for later use

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(le,file)

with open('onehot_encoding_geo.pkl','wb') as file:
    pickle.dump(ohe,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

#### regression problem statement

In [76]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [77]:
#build the model
model = Sequential([
    Dense(64,activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

In [78]:
from streamlit import metric
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 64)                832

 dense_10 (Dense)            (None, 32)                2080

 dense_11 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [79]:
from datetime import datetime
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
##setup the tensorboard

log_dir = "Regressionlogs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [80]:
##early stopping

early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [81]:
#train the model

history = model.fit(
    X_train,y_train,
    validation_data=[X_test,y_test],
    epochs = 100,
    callbacks = [early_stopping_callback,tensorflow_callback])

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 100377.1172 - mae: 100377.1172 - val_loss: 98514.5938 - val_mae: 98514.5938
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 99628.7031 - mae: 99628.7031 - val_loss: 97007.0703 - val_mae: 97007.0703
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 97032.2109 - mae: 97032.2109 - val_loss: 93199.6797 - val_mae: 93199.6797
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 91933.6094 - mae: 91933.6094 - val_loss: 86840.7422 - val_mae: 86840.7422
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 84512.7422 - mae: 84512.7422 - val_loss: 78699.0312 - val_mae: 78699.0312
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 75706.7578 - mae: 75706.7578 - val_loss: 70176.2734 - val_mae: 70176.2734
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 67109.9922 - mae: 67109.9922 - val_loss: 62611.8242 - val_mae: 62611.8242
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 60147.8633 - mae: 60147.8633 - val_loss: 57119.7695 - val_mae: 57119.7695
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 55514.4258 - mae: 55514.4258 - val_loss: 53858.5469 - val_mae: 53858.5469
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 52937.4688 - mae: 52937.4688 - val_loss: 52194.4648 - val_mae: 52194.4648
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 51678.8203 - mae: 51678.8203 - val_loss: 51432.4023 - val_mae: 51432.4023
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 51083.1914 - mae: 51083.1914 - val_loss: 51109.1875 - val_mae: 51109.1875
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50777.9492 - mae: 50777.9492 - val_loss: 50970.7227 - val_mae: 50970.7227
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 50596.6445 - mae: 50596.6445 - val_loss: 50902.1016 - val_mae: 50902.1016
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 50477.3594 - mae: 50477.3594 - val_loss: 50848.0000 - val_mae: 50848.0000
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 50390.1719 - mae: 50390.1719 - val_loss: 50789.5859 - val_mae: 50789.5859
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 50321.0117 - mae: 50321.0117 - val_loss: 50731.7891 - val_mae: 50731.7891
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 50265.8320 - mae: 50265.8320 - val_loss: 50685.8828 - val_mae: 50685.8828
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 50210.0742 - mae: 50210.0742 - val_loss: 50649.5156 - val_mae: 50649.5156
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 50162.8438 - mae: 50162.8438 - val_loss: 50611.1680 - val_mae: 50611.1680
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 50124.0156 - mae: 50124.0156 - val_loss: 50576.2734 - val_mae: 50576.2734
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 50084.7812 - mae: 50084.7812 - val_loss: 50550.1094 - val_mae: 50550.1094
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 50047.1758 - mae: 50047.1758 - val_loss: 50524.0703 - val_mae: 50524.0703
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 50016.0703 - mae: 50016.0703 - val_loss: 50503.6953 - val_mae: 50503.6953
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49983.5586 - mae: 49983.5586 - val_loss: 50484.1875 - val_mae: 50484.1875
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49951.4766 - mae: 49951.4766 - val_loss: 50449.8633 - val_mae: 50449.8633
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 49927.1250 - mae: 49927.1250 - val_loss: 50430.8398 - val_mae: 50430.8398
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49904.9805 - mae: 49904.9805 - val_loss: 50420.0625 - val_mae: 50420.0625
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49878.1719 - mae: 49878.1719 - val_loss: 50412.1289 - val_mae: 50412.1289
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 49856.0117 - mae: 49856.0117 - val_loss: 50392.5273 - val_mae: 50392.5273
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49832.7891 - mae: 49832.7891 - val_loss: 50382.4141 - val_mae: 50382.4141
Epoch 32/100
250/250 [==============================] - 1s 4ms/step - loss: 49815.3594 - mae: 49815.3594 - val_loss: 50364.8828 - val_mae: 50364.8828
Epoch 33/100
250/250 [==============================] - 1s 4ms/step - loss: 49792.9023 - mae: 49792.9023 - val_loss: 50357.6211 - val_mae: 50357.6211
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49777.7188 - mae: 49777.7188 - val_loss: 50354.0625 - val_mae: 50354.0625
Epoch 35/100
250/250 [==============================] - 1s 2ms/step - loss: 49758.6289 - mae: 49758.6289 - val_loss: 50338.9922 - val_mae: 50338.9922
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 49743.8750 - mae: 49743.8750 - val_loss: 50321.9258 - val_mae: 50321.9258
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 49725.4062 - mae: 49725.4062 - val_loss: 50329.5117 - val_mae: 50329.5117
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 49710.8203 - mae: 49710.8203 - val_loss: 50327.5938 - val_mae: 50327.5938
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 49694.5742 - mae: 49694.5742 - val_loss: 50313.2188 - val_mae: 50313.2188
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 49683.3633 - mae: 49683.3633 - val_loss: 50297.6289 - val_mae: 50297.6289
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 49671.4648 - mae: 49671.4648 - val_loss: 50305.0312 - val_mae: 50305.0312
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 49659.6719 - mae: 49659.6719 - val_loss: 50301.2578 - val_mae: 50301.2578
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 49646.5000 - mae: 49646.5000 - val_loss: 50306.4062 - val_mae: 50306.4062
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 49633.3750 - mae: 49633.3750 - val_loss: 50298.3047 - val_mae: 50298.3047
Epoch 45/100
250/250 [==============================] - 1s 2ms/step - loss: 49621.8125 - mae: 49621.8125 - val_loss: 50298.9492 - val_mae: 50298.9492
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 49611.3125 - mae: 49611.3125 - val_loss: 50292.0312 - val_mae: 50292.0312
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 49603.0859 - mae: 49603.0859 - val_loss: 50287.7148 - val_mae: 50287.7148
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49591.8555 - mae: 49591.8555 - val_loss: 50289.2969 - val_mae: 50289.2969
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 49583.8086 - mae: 49583.8086 - val_loss: 50286.3750 - val_mae: 50286.3750
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 49573.6289 - mae: 49573.6289 - val_loss: 50287.9336 - val_mae: 50287.9336
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 49567.1992 - mae: 49567.1992 - val_loss: 50281.0742 - val_mae: 50281.0742
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 49557.2930 - mae: 49557.2930 - val_loss: 50286.4062 - val_mae: 50286.4062
Epoch 53/100
250/250 [==============================] - 1s 2ms/step - loss: 49549.7422 - mae: 49549.7422 - val_loss: 50287.4336 - val_mae: 50287.4336
Epoch 54/100
250/250 [==============================] - 1s 2ms/step - loss: 49543.8086 - mae: 49543.8086 - val_loss: 50283.0156 - val_mae: 50283.0156
Epoch 55/100
250/250 [==============================] - 1s 2ms/step - loss: 49533.5742 - mae: 49533.5742 - val_loss: 50291.5703 - val_mae: 50291.5703
Epoch 56/100
250/250 [==============================] - 1s 2ms/step - loss: 49527.4688 - mae: 49527.4688 - val_loss: 50293.2578 - val_mae: 50293.2578
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 49519.0000 - mae: 49519.0000 - val_loss: 50283.1602 - val_mae: 50283.1602
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 49516.2266 - mae: 49516.2266 - val_loss: 50290.6406 - val_mae: 50290.6406
Epoch 59/100
250/250 [==============================] - 1s 2ms/step - loss: 49503.9023 - mae: 49503.9023 - val_loss: 50287.5664 - val_mae: 50287.5664
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 49499.8281 - mae: 49499.8281 - val_loss: 50289.3203 - val_mae: 50289.3203
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 49490.2969 - mae: 49490.2969 - val_loss: 50289.3164 - val_mae: 50289.3164

In [82]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [83]:
%reload_ext tensorboard

%tensorboard --logdir Regressionlogs\fit

Reusing TensorBoard on port 6006 (pid 18372), started 4:01:58 ago. (Use '!kill 18372' to kill it.)

In [84]:
test_loss,test_mae = model.evaluate(X_test,y_test)
print(test_loss,test_mae)

63/63 [==============================] - 0s 2ms/step - loss: 50281.0742 - mae: 50281.0742
50281.07421875 50281.07421875

In [85]:
model.save('regression_model.h5')

d:\mohit\AIML\ann classifier\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(